export default function CardForm(props) {
  return (
    <form onSubmit={props.handleSubmit} className="card-form">
      {props.onCancel && <p>Edit Card</p>}
      {!props.onCancel && <p>Create a New Card</p>}
      <table className="card-form-table">
        <tr>
          <td>Name</td>
          <td>
            <label>
              <input
                name="fullname"
                type="text"
                required="required"
                onChange={props.handleChange}
              />
            </label>
          </td>
        </tr>
        <tr>
          <td>Email</td>
          <td>
            <label>
              <input
                name="email"
                type="email"
                onChange={props.handleChange}
              />
            </label>
          </td>
        </tr>
        <tr>
          <td>Photo</td>
          <td>
            <label>
              <input
                name="photo"
                type="text"
                onChange={props.handleChange}
              />
            </label>
          </td>
        </tr>
        <tr>
          <td>Title</td>
          <td>
            <label>
              <input
                name="title"
                type="text"
                onChange={props.handleChange}
              />
            </label>
          </td>
        </tr>
        <tr>
          <td>Company</td>
          <td>
            <label>
              <input
                name="company"
                type="text"
                onChange={props.handleChange}
              />
            </label>
          </td>
        </tr>
        <tr>
          <td>Phone</td>
          <td>
            <label>
              <input
                name="phone"
                type="tel"
                onChange={props.handleChange}
              />
            </label>
        </td>
        </tr>
        <tr>
          <td>GitHub</td>
          <td>
            <label>
              <input
                name="github"
                type="text"
                onChange={props.handleChange}
              />
            </label>
          </td>
        </tr>
        <tr>
          <td>LinkedIn</td>
          <td>
            <label>
              <input
                name="linkedin"
                type="text"
                onChange={props.handleChange}
              />
            </label>
          </td>
        </tr>
        <tr>
          <td>Facebook</td>
          <td>
            <label>
              <input
                name="facebook"
                type="text"
                onChange={props.handleChange}
              />
            </label>
          </td>
        </tr>
        <tr>
          <td>Instagram</td>
          <td>
            <label>
              <input
                name="instagram"
                type="text"
                onChange={props.handleChange}
              />
            </label>
          </td>
        </tr>
        <tr>
          <td>Bio</td>
          <td>
            <label>
              <input
                name="bio"
                type="text"
                onChange={props.handleChange}
              />
            <br />
          </label>
        </td>
        </tr>
      </table>
        <input className="card-form-submit" type="submit" value="Submit" />
      <br />
        {props.onCancel &&
          <button className="card-form-cancel" onClick={props.onCancel}>Cancel</button>
        }
    </form>
  )
}